name: Testing laravel application with Breeze starterkit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        stack: [blade]
        laravel: [10]
        args: [""]
            
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:^${{ matrix.laravel }} .
          composer require laravel/breeze:@dev --no-interaction --no-update
          composer config repositories.breeze '{"type": "path", "url": "breeze"}' --file composer.json
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'breeze'

      - name: Install Breeze
        run: |
          composer update "laravel/breeze" --prefer-dist --no-interaction --no-progress -W
          php artisan breeze:install ${{ matrix.stack }} ${{ matrix.args }}
      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build

      - name: Install Composer Dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
